### ISSUE TITLE
KeyError in 'Fantasy_Stats.py'

### ISSUE THREAD

**Issue by chanalytics-ai** [yahoo-fantasy/nfl-fantasy-football#11]
Hey There,

Noticing an error when trying to run the 'fantasy_stats.py' script. Not sure if this is a similar error to the one reported before in Issue #4 

> Traceback (most recent call last):
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 307, in <module>
>     main()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 275, in main
>     bot.run()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 298, in run
>     UD.UpdateTransactions()
>   File "/Users/williamchan/PycharmProjects/cll/fantasy_stats.py", line 54, in UpdateTransactions
>     old_trans = old_transactions['fantasy_content']['league'][1]['transactions']['count']
> KeyError: 'fantasy_content'

Thanks for taking a look!

**Comment by chanalytics-ai** [comment]
Context - I'm running it for NHL and it seems like fantasy_stats.py isn't taking the right game_key from yahoogameinfo.json

from yahoogameinfo.json
> {"fantasy_content": {"xml:lang": "en-US", "yahoo:uri": "/fantasy/v2/games;game_codes=nhl;seasons=2019", "games": {"0": {"game": [{"game_key": "396", "game_id": "396", "name": "Hockey", "code": "nhl", "type": "full", "url": "https://hockey.fantasysports.yahoo.com/2019/hockey", "season": "2019", "is_registration_over": 1, "is_game_over": 1, "is_offseason": 1}]}, "count": 1}, "time": "22.650003433228ms", "copyright": "Data provided by Yahoo! and STATS, LLC", "refresh_rate": "60"}}

from league.json

> {"error": {"xml:lang": "en-us", "yahoo:uri": "/fantasy/v2/league/411.l.6767/?format=json", "description": "You are not allowed to view this page because you are not in this league.", "detail": ""}}

**Comment by chanalytics-ai** [comment]
Figured out the issue with this error. If you're going back in history, make sure all the URLs reflect the example below in fantasy_stats.py and get_league_info.py

    def UpdateYahooLeagueInfo(self):
        # UPDATE LEAGUE GAME ID
        yahoo_api._login()
        url = 'https://fantasysports.yahooapis.com/fantasy/v2/games;game_codes=nhl;seasons=2019'
        response = oauth.session.get(url, params={'format': 'json'})
        r = response.json()
        with open('YahooGameInfo.json', 'w') as outfile:
            json.dump(r, outfile)
