### ISSUE TITLE
JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by ker0k3n0** [yahoo-fantasy/nfl-fantasy-football#18]
Good day,
I am very new to Python but I found your fantasy football and I was trying to pull stats for my friend. I got an error when I tried to run the fantasy_stats.py and it is related to JSONDecodeError. Can anyone help me with this? It is not in your instruction. Do I need to do something with the json\decoder.py?

Here is the output when I ran the fantasy_stats.py
-------------------------------------------------------------
C:\Users\ker0k\OneDrive\Documents\Python>py fantasy_stats.py
[2023-09-02 09:43:58,181 DEBUG] [yahoo_oauth.oauth.__init__] Checking
[2023-09-02 09:43:58,181 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 38379.630049705505
[2023-09-02 09:43:58,181 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN HAS EXPIRED
[2023-09-02 09:43:58,181 DEBUG] [yahoo_oauth.oauth.refresh_access_token] REFRESHING TOKEN
[2023-09-02 09:43:58,450 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 0.26961612701416016
[2023-09-02 09:43:58,450 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
Yahoo League Info Updated
[2023-09-02 09:43:58,813 DEBUG] [yahoo_oauth.oauth.__init__] Checking
[2023-09-02 09:43:58,820 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 0.6397476196289062
[2023-09-02 09:43:58,820 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
[2023-09-02 09:43:58,826 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 0.6458017826080322
[2023-09-02 09:43:58,826 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
League update - Done
[2023-09-02 09:43:59,177 DEBUG] [yahoo_oauth.oauth.__init__] Checking
[2023-09-02 09:43:59,177 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 0.9960055351257324
[2023-09-02 09:43:59,177 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
[2023-09-02 09:43:59,177 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 0.9960055351257324
[2023-09-02 09:43:59,177 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
Standings update - Done
[2023-09-02 09:43:59,554 DEBUG] [yahoo_oauth.oauth.__init__] Checking
[2023-09-02 09:43:59,568 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 1.3874835968017578
[2023-09-02 09:43:59,568 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
[2023-09-02 09:43:59,571 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 1.3899612426757812
[2023-09-02 09:43:59,571 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
Scoreboards update - Done
Traceback (most recent call last):
  File "C:\Users\ker0k\OneDrive\Documents\Python\fantasy_stats.py", line 307, in <module>
    main()
  File "C:\Users\ker0k\OneDrive\Documents\Python\fantasy_stats.py", line 275, in main
    bot.run()
  File "C:\Users\ker0k\OneDrive\Documents\Python\fantasy_stats.py", line 298, in run
    UD.UpdateTransactions()
  File "C:\Users\ker0k\OneDrive\Documents\Python\fantasy_stats.py", line 28, in UpdateTransactions
    old_transactions = json.load(load_file)
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ker0k\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ker0k\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ker0k\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ker0k\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea?

**Comment by ker0k3n0** [comment]
I figured it out
